### ISSUE TITLE
Avoiding shutdown because too hot

### ISSUE THREAD

**Issue by livexia** [jlempen/Surface-Go-2-OpenCore#16]
After disable BD PROCHOT and using voltageshift by running `sudo ./voltageshift buildlaunchd -120 -50 -80 0 0 0 1 28 18 0.002 60`. System still shutdown due to the hot(around 85c).

After some trying, I think the power limit pl should be around 7 and pl2 should be 10(or
 unlimit). After stress test, with undervoltage, cpu temp will quickly approach 80, then pl1 activate, temp wil drop to 78.

So I think apply pl1 is a good way to avoid shutdown while also have ok performance.

**Comment by jlempen** [comment]
Sorry @livexia, I've only seen this thread today.

I must admit that I don't use my SGO2 for much more than checking my mail and very mild websurfing with one or two tabs open in Firefox, so I've never reached critical temperatures, apart from the installation process and updates.

If you can confirm that your suggested settings are better than those in my readme, please make a pull request in this repo, your PR's are more than welcome.

Thanks again!

**Comment by livexia** [comment]
I also apologize for reinstalling Linux since the last installation test, so I can't say for sure now, I will close issue.
