### ISSUE TITLE
I would like to ask if the Pentium 4425y will work

### ISSUE THREAD

**Issue by Anglos333** [jlempen/Surface-Go-2-OpenCore#18]

**Comment by jlempen** [comment]
The 4425Y CPU could perhaps be spoofed, but the bigger issue here is that its iGPU is totally unsupported, thus you would have no graphics acceleration, which would make the already anemic performance of the 4425Y unbearably slow.

If you want a usable Surface Go 2 running macOS, you'd be better off finding a second hand i3 version, they can be found for very cheap these days.
