### ISSUE TITLE
Cannot upgrade to Sequoia

### ISSUE THREAD

**Issue by summerboard505** [jlempen/Surface-Go-2-OpenCore#19]
So I've successfully installed Ventura on my Surface Go 2, but now I wanted to upgrade it to Sequoia. I tried several methods (internet recovery, offline installer upgrade...), but all I get when trying every of these is a back screen with a prohibited (no-no) symbol.
What am I doing wrong?

**Comment by jlempen** [comment]
The "MacBookAir8,1" SMBIOS this repository uses for the SGO2 (because it's the closest to our hardware) is only supported up to macOS Sonoma. The latest macOS Sequoia dropped support for the 2018 and earlier MacBook Airs using this SMBIOS.
It might be possible to change the SMBIOS to something like "MacBookAir9,1" or "MacBookPro16,2" which use Ice Lake CPUs and are still compatible with macOS Sequoia. This could break hardware accelerated graphics on the iGPU, though.
I'll have a closer look at this when I update the repo with the latest OC and kexts in the near future.

**Comment by summerboard505** [comment]
Thanks! I have noticed that the 2018 Mac mini is supported by Sequoia, and it uses UHD 630 (probably the same family). I think we can use that

**Comment by summerboard505** [comment]
Well. I thought about it, and I think macOS won't detect the battery with a Mac mini SMBIOS. So I think we should use MacBook Pro 2018 SMBIOS as it's UHD 630 too

**Comment by summerboard505** [comment]
I have changed the SMBIOS to MacBookPro16,4 and I got the installer booting. But I cannot connect to Wi-Fi and use the Type Cover.

**Comment by jlempen** [comment]
OK, good to know it's booting with the `MacBookPro16,4` SMBIOS. Please note that you'll need to change the SMBIOS in the `info.plist` file inside `USBMap.kext` as well or the USB mapping won't work anymore.

For the Intel Wi-Fi to work in Sequoia, you'll need to disable all `AirportItlwm-***.kext` and use [the latest itlwm.kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0/itlwm_v2.3.0_stable.kext.zip) and its companion app [HeliPort.dmg](https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.5.0/HeliPort.dmg) from the OpenIntelWireless project instead. Please read https://openintelwireless.github.io/ to learn more about the pros and cons of `AirportItlwm.kext` vs `itlwm.kext + HeliPort`. 
For instance, `itlwm.kext` won't work in the installer and recovery so you'll need to have a USB thumbdrive with the full Sequoia installer on hand.

To fix the Type Cover, you'll need to replace the `VoodooInput.kext` PlugIn inside `VoodooI2C-SurfaceTouch.kext` with [the latest release of VoodooInput from Acidanthera](https://github.com/acidanthera/VoodooInput/releases/download/1.1.6/VoodooInput-1.1.6-RELEASE.zip).

I'll try to update the repo over the week-end to add compatibility with macOS Sequoia.

**Comment by jlempen** [comment]
By the way, the latest version of `itlwm.kext` is actually already included in my EFI folder :-) All you need to do is disable `AirportItlwm-***.kext` and enable `itlwm.kext` and install the HeliPort app to connect to networks.

**Comment by summerboard505** [comment]
Before all of this happened, I have started an Upgrade to Sequoia, so I was able to successfully complete it, but it is incredibly slow and I have no Lockscreen wallpaper.

**Comment by summerboard505** [comment]
I think there's no graphics driver as the wallpaper is also missing, and the dock is not transparent

**Comment by jlempen** [comment]
> but it is incredibly slow and I have no Lockscreen wallpaper.

That's most certainly because you're lacking hardware accelerated graphics. To check, look at the "Graphics" section in "About This Mac". If you have accelerated graphics, it should tell something such as "Intel(R) HD Graphics 615 1536 MB".

**Comment by summerboard505** [comment]
It's saying I've got Intel HD Graphics KBL CRB 1536 MB. Something's not right

**Comment by jlempen** [comment]
I don't have my SGO2 on hand right now, but I believe "Intel HD Graphics KBL CRB 1536 MB" is actually what's displayed in Ventura and Sonoma as well. KBL means Kaby Lake which is the correct Intel CPU generation for the 8100Y GPU... 
You might try changing the `AAPL,ig-platform-id` and/or add a `device-id` and try spoofing another iGPU (https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#deviceproperties and https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-uhd-graphics-610-650-kaby-lake-and-amber-lake-y-processors)

**Comment by summerboard505** [comment]
I have applied the changes you told me to, but now it's just stuck at the apple logo on boot. No progress bar, no nothing, and after 10 mins it just reboots.

**Comment by summerboard505** [comment]
I can't even enable verbose boot, it's very stuck at that screen

**Comment by summerboard505** [comment]
Maybe I should try reverting?

**Comment by summerboard505** [comment]
Nevermid. Got it to boot (forgot to remove loose kext entries for airportitlwm) and verbose finally says something. It"s trying 50 times to begin gfx firmware load process. There is no graphics acceleration. I've tried replacing ig-platform-id with UHD 630 and 620 but it didn't work. When I replaced it with UHD 630 it started saying Graphics 7 MB. I haven't tried replacing the device id yet but when I get home I will try it.

**Comment by jlempen** [comment]
Thanks for all your feedback, @summerboard505.
Glad you got've got it to boot.

Getting the Amber Lake HD 615 of our SGO2 to work in Sequoia now official support for it has been removed is gonna be tricky. 

Perhaps OpenCore-Legacy-Patcher could bring back support for the Amber Lake 8100Y CPU and HD 615 iGPU.

Until then, I would recommend staying on Ventura or Sonoma for the time being.

**Comment by summerboard505** [comment]
Also I wanted to ask, how to contribute to the project?

**Comment by jlempen** [comment]
@summerboard505, any contribution you make to this repo through pull requests is welcome if you find something to add or improve :-)

**Comment by summerboard505** [comment]
Alright. I'll close this issue
