### ISSUE TITLE
Trackpad and keyboard not working on Monterey on Go 2

### ISSUE THREAD

**Issue by felixding** [jlempen/Surface-Go-2-OpenCore#2]
They worked fine on the Open Core boot screen, but stopped working completely once Mac OS booted into the installation UI, as if no Type Cover was connected.

Un/replug Type Cover didn't help. But the touch screen was fine.

I have tried to replace `VoodooI2C.kext` and `VoodooI2CHID.text` from https://github.com/jlempen/Surface-Go-2-OpenCore/issues/1#issuecomment-1705597716 but still no luck.

Replacing VoodooI2C with the latest 2.8 version and rebuilding the config.plist accordingly didn't work either, unfortunately.

**Comment by felixding** [comment]
OK. Never mind, it's now working on OC 0.8.8. I was previously using 0.9.7.

**Comment by jlempen** [comment]
Hey @felixding 
The trackpad and keyboard should work just fine on the latest OC 0.9.7 and with up to date kexts, but only if you keep the original `VoodooI2C.kext` and `VoodooI2CHID.text` from this repo. Those are patched for the Surface Type Cover.
I've played with the other kexts mentioned in [this thread](https://github.com/jlempen/Surface-Go-2-OpenCore/issues/1#issuecomment-1705597716), but none has been working for me.
I'll update my repo in the next few days with the latests OC, kexts and the hibernation patches if I can get them to work reliably.

**Comment by lazd** [comment]
FYI The version of `VoodooI2C` and `VoodooI2CHID` I recently contributed are built straight from `master`, there are no Surface-specific typecover patches. As such, when VoodooI2C 2.9 is released, you'll be able to upgrade to it and will not longer need my locally build kexts. Cheers!

**Comment by felixding** [comment]
Thanks for the update. That'll be great.

**Comment by jlempen** [comment]
Good to know this, @lazd. I'll remove the added "-SurfaceTouch" from the `VoodooI2C-SurfaceTouch.kext` and `VoodooI2CHID-SurfaceTouch.kext`filenames once VoodooI2c v2.9 is released. That way, tools such as OCAT will auto-update those kexts automagically.
