### ISSUE TITLE
Surface pen doesn't work

### ISSUE THREAD

**Issue by lazd** [jlempen/Surface-Go-2-OpenCore#5]
It just does nothing... I think it may have been broken in VoodoI2C 2.7 (see https://github.com/VoodooI2C/VoodooI2C/issues/500), or perhaps I broke it when I removed this `for` loop in https://github.com/VoodooI2C/VoodooI2CHID/pull/69 (which was fixed in https://github.com/VoodooI2C/VoodooI2CHID/pull/73).

In any case, we need to build `VoodooI2CHID` from the `master` branch and see if it's fixed. I'm working on that now, but unfortunately XCode 15.2 on Sonoma doesn't have `IOKit`, so I can't build it at the moment. I'll figure something out and will test/send a PR with the updated kexts if it works.

**Comment by lazd** [comment]
Sure enough, rebuilding VoodooI2CHID from the latest master fixed it! PR sent.

**Comment by lazd** [comment]
@jlempen note that, although the stylus works for hovering, dragging, right clicking, and the eraser seems to perform a different function (in [Krita](https://krita.org/en/download/krita-desktop/), it pans the canvas), I can't seem to verify that pressure works. I know my stylus and the Surface Go 2 support it, and after a quick glance at the code, it does seem we're at least trying to read/report it, but alas, it has no effect. Any insight on how to test properly?

**Comment by jlempen** [comment]
I'm by no means an expert in the matter, I can only confirm that the stylus is working with your latest build of VoodooI2C. I don't think that pressure and tilt are working. 
Maybe [Xiashangning](https://github.com/Xiashangning), the author of the [BigSurface](https://github.com/Xiashangning/BigSurface) kext would know how to fix this.

**Comment by lazd** [comment]
I can definitely look at this at the VoodooI2C level, I'll add some logs and see what it outputs. But I wonder what the best way to test is...

**Comment by NotMifa** [comment]
Hey @lazd , i used your new kexts and it totally worked for me..! On a Lenovo Thinkpad L13 yoga btw... 

Any chance I could share your 'surface repo' with a couple of friends? They were having this issue too and this would greatly help.. 

Also, I think it would be great if you can follow up on https://github.com/VoodooI2C/VoodooI2C/issues/500 , would close the issue at voodoo I2C's end... 

Thanks once again for the compiled master kext..!

**Comment by lazd** [comment]
@NotMifa glad to hear my kexts are working for you, did you also test stylus support? As far as the VoodooI2C release, I believe it's coming but I'm only a contributor and don't have any control of when they release it.

Although it would be great if they got 2.9 out with this and other fixes, you can always pull main and build it locally yourself, it's not hard, all you need is XCode, [documentation is here](https://github.com/VoodooI2C/VoodooI2C/blob/master/Documentation/Build%20Environment.md). Good luck!
